//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamCompanion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1883")]
        public int EmbeddedMqttBrokerPort {
            get {
                return ((int)(this["EmbeddedMqttBrokerPort"]));
            }
            set {
                this["EmbeddedMqttBrokerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mySecretUser")]
        public string EmbeddeMqttBrokerUserName {
            get {
                return ((string)(this["EmbeddeMqttBrokerUserName"]));
            }
            set {
                this["EmbeddeMqttBrokerUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mySecretPassword")]
        public string EmbeddedMqttBrokerSecretPassword {
            get {
                return ((string)(this["EmbeddedMqttBrokerSecretPassword"]));
            }
            set {
                this["EmbeddedMqttBrokerSecretPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExternalMqttBrokerName {
            get {
                return ((string)(this["ExternalMqttBrokerName"]));
            }
            set {
                this["ExternalMqttBrokerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1883")]
        public int ExternalMqttBrokerPort {
            get {
                return ((int)(this["ExternalMqttBrokerPort"]));
            }
            set {
                this["ExternalMqttBrokerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExternalMqttBrokerUserName {
            get {
                return ((string)(this["ExternalMqttBrokerUserName"]));
            }
            set {
                this["ExternalMqttBrokerUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExternalMqttBrokerSecretPassword {
            get {
                return ((string)(this["ExternalMqttBrokerSecretPassword"]));
            }
            set {
                this["ExternalMqttBrokerSecretPassword"] = value;
            }
        }
    }
}
